# Generated by Django 3.1.7 on 2021-05-02 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome_Categoria', models.CharField(max_length=50)),
                ('Codigo_Categoria', models.IntegerField()),
            ],
            options={
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome_Produto', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('Preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Categoria_Produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='e_commerce.categoria')),
            ],
            options={
                'db_table': 'produto',
            },
        ),
    ]
